CREATE DATABASE dnrn_db;

USE dnrn_db;


CREATE TABLE USER
(
ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(45),
LAST_NAME VARCHAR(45),
EMAIL VARCHAR(45),
PASSWORD VARCHAR(256), 
PRIMARY KEY (ID),
UNIQUE KEY (EMAIL)
)

CREATE TABLE CITIZEN
(
  ID INT  NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20) NOT NULL,
  SEX VARCHAR(20),
  DOB DATE  NOT NULL,
  WEIGHT INT,
  FATHERS_NAME VARCHAR(20),
  MOTHERS_NAME VARCHAR(20),
  PROVINCE VARCHAR(45) NOT NULL,
  DISTRICT VARCHAR(45),
  VILLAGE VARCHAR(45),
  DESCRIPTIO VARCHAR(45),
  PRIMARY KEY (ID)
)


CREATE TABLE BIRTH_CERTIFICATE
(
  ID INT  NOT NULL AUTO_INCREMENT,
  NUIC VARCHAR(45) NOT NULL,
  REGISTR_CONSERVAT VARCHAR(256),
  REGISTR_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  STATE_CITIZEN VARCHAR(20),
  ENDORSMENT VARCHAR(256),
  ADDRESS VARCHAR(60),
  DESCRIPTIO VARCHAR(45),
  CITIZEN_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (CITIZEN_ID) REFERENCES CITIZEN(ID) ON DELETE CASCADE
)
